

services:
    spring_boot:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: ./.env
        ports:
            - 8081:8081
        restart:
            always
        environment:
             - GOOGLE_API_KEY=$GOOGLE_API_KEY